;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev
#default_envs = lilygo-t-display-s3

; Base environment - common settings shared by all board specializations.
[env]
platform = espressif32@6.9.0
framework = arduino
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 921600
monitor_filters = log2file, time, default

build_flags =
  -O2
  -D IOTWEBCONF_PASSWORD_LEN=64
  -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
  
lib_deps =
  bodmer/TFT_eSPI@^2.5.33
  lvgl/lvgl@^8.3.9
  bblanchon/ArduinoJson@^6.21.3
  prampec/IotWebConf@^3.2.1
  rzeldent/micro-http-status@^1.0.2
  rzeldent/micro-moustache@^1.0.0
  rzeldent/micro-timezonedb@^1.0.4

board_build.embed_files =
  html/bootstrap.min.css.gz

board_build.embed_txtfiles =
  html/index.html

[env:esp32dev]
board = esp32dev
build_flags =
  ${env.build_flags}
  # GPIO of the buttons on the TTGO Display
  -D GPIO_BUTTON_TOP=35
  -D GPIO_BUTTON_BOTTOM=0
  # SD Card definitions
  -D SD_CARD_CS=33
  -D SD_CARD_SCLK=25
  -D SD_CARD_MISO=27
  -D SD_CARD_MOSI=26
  # ADC detection enable port and ADC GPIO
  -D GPIO_ADC_EN=14
  -D GPIO_ADC_IN=34
  # TFT_eSPI settings
  -D USER_SETUP_LOADED
  -D ST7789_DRIVER
  -D TFT_WIDTH=135
  -D TFT_HEIGHT=240
  -D CGRAM_OFFSET
  -D TFT_MOSI=19
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=16
  -D TFT_RST=23
  -D TFT_BL=4
  -D TOUCH_CS=-1
  -D TFT_BACKLIGHT_ON=HIGH
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=6000000
  # LVGL settings
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -I "${PROJECT_INCLUDE_DIR}"
  -D LV_CONF_PATH=lv_conf.h
  -D LV_HOR_RES_MAX=240
  -D LV_VER_RES_MAX=135

[env:lilygo-t-display-s3]
board = lilygo-t-display-s3
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
build_flags =
  ${env.build_flags}
  # GPIO of the buttons on the TTGO Display
  -D GPIO_BUTTON_TOP=14
  -D GPIO_BUTTON_BOTTOM=0
  # TFT_eSPI settings
  -D USER_SETUP_LOADED=1
  -D ST7789_DRIVER
  -D CGRAM_OFFSET
  -D TFT_RGB_ORDER=TFT_BGR
  -D TFT_INVERSION_ON
  -D TFT_PARALLEL_8_BIT
  -D TFT_WIDTH=170
  -D TFT_HEIGHT=320
  -D TFT_DC=7
  -D TFT_RST=5
  -D TFT_WR=8
  -D TFT_RD=9
  -D TFT_D0=39
  -D TFT_D1=40
  -D TFT_D2=41
  -D TFT_D3=42
  -D TFT_D4=45
  -D TFT_D5=46
  -D TFT_D6=47
  -D TFT_D7=48
  -D TFT_BL=38
  -D TFT_BACKLIGHT_ON=HIGH
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=6000000
  # LVGL settings
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -I "${PROJECT_INCLUDE_DIR}"
  -D LV_CONF_PATH=lv_conf.h
  -I "${PROJECT_INCLUDE_DIR}"
  -D LV_CONF_PATH=lv_conf.h
  -D LV_HOR_RES_MAX=320
  -D LV_VER_RES_MAX=170

[env:lilygo-t-display-s2-t8]
board = esp32-s2-saola-1
board_build.f_cpu = 240000000L ; ESP32-S2 is capable of running at 240MHz, but the default is 120MHz. This line sets the CPU frequency to 240MHz for better performance
board_build.f_psram = 80000000L ; ESP32-S2 supports PSRAM at 80MHz, so this line sets the PSRAM frequency to 80MHz for optimal performance
board_build.arduino.memory_type = qio_qspi ; 'sdkconfig.h' errors means that memory_type selection is not in accordance with microcontroller supported memory types
monitor_speed = 115200
upload_speed = 115200
upload_flags = --no-stub ; The ESP32-S2 was particularly tricky to flash. Old CP2102 USB 2 TTL UART dind't work for me. Only newer CP2104 USB 2 TTL UART did the magic with this "--no-stub" flag or direct USB connection (with USB OTG microswitch activated)
                         ; Refer to https://github.com/Xinyuan-LilyGO/LilyGo-T-Display-S2/issues/1 for UART TX/RX pinout connections
build_flags =
  ${env.build_flags}
  -D BOARD_HAS_PSRAM=1
  -D ARDUINO_USB_CDC_ON_BOOT=1 ; Pushes Serial Monitor output to the native USB-C port instead of the UART pins, which is useful for debugging and logging
  -D ARDUINO_USB_MSC_ON_BOOT=0 ; Deactivates the USB Mass Storage mode on boot, which prevents the device from being recognized as a storage device when connected to a computer, allowing for proper USB communication for debugging and logging
  # GPIO of the buttons on the TTGO Display S2 T8
  -D GPIO_BUTTON_TOP=0
  -D GPIO_BUTTON_BOTTOM=-1 ; Not used on this board. The second button is connected to the Reset pin, so it cannot be used for other purposes. The GPIO_BUTTON_TOP is defined as -1, which is not a valid GPIO pin for the ESP32-S2, but it is used to indicate that the button is not available for use in the code
  # TFT_eSPI settings
  -D USER_SETUP_LOADED=1
  -D ST7789_DRIVER
  -D CGRAM_OFFSET
  -D TFT_RGB_ORDER=TFT_BGR
  -D TFT_INVERSION_ON
  -D TFT_WIDTH=135
  -D TFT_HEIGHT=240
	-D TFT_MOSI=35
	-D TFT_SCLK=36
	-D TFT_CS=34
	-D TFT_DC=37
	-D TFT_RST=38
	-D TFT_BL=33
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=6000000
  # LVGL settings
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -I "${PROJECT_INCLUDE_DIR}"
  -D LV_CONF_PATH=lv_conf.h
  -D LV_HOR_RES_MAX=240
  -D LV_VER_RES_MAX=135
