#include <str.h>

struct country
{
    const char *id;
    const char *name;
};

static const country countries[] = {
    {"BQ", "Bonaire, Saint Eustatius and Saba"},
    {"AW", "Aruba"},
    {"AG", "Antigua and Barbuda"},
    {"AE", "United Arab Emirates"},
    {"AF", "Afghanistan"},
    {"DZ", "Algeria"},
    {"AZ", "Azerbaijan"},
    {"AL", "Albania"},
    {"AM", "Armenia"},
    {"AO", "Angola"},
    {"AS", "American Samoa"},
    {"AR", "Argentina"},
    {"AU", "Australia"},
    {"AT", "Austria"},
    {"AI", "Anguilla"},
    {"AQ", "Antarctica"},
    {"BH", "Bahrain"},
    {"BB", "Barbados"},
    {"BW", "Botswana"},
    {"BM", "Bermuda"},
    {"BE", "Belgium"},
    {"BS", "Bahamas"},
    {"BD", "Bangladesh"},
    {"BZ", "Belize"},
    {"BA", "Bosnia and Herzegovina"},
    {"BO", "Bolivia"},
    {"MM", "Myanmar"},
    {"BJ", "Benin"},
    {"BY", "Belarus"},
    {"SB", "Solomon Islands"},
    {"BR", "Brazil"},
    {"IN", "India"},
    {"BT", "Bhutan"},
    {"BG", "Bulgaria"},
    {"BV", "Bouvet Island"},
    {"BN", "Brunei Darussalam"},
    {"BI", "Burundi"},
    {"CA", "Canada"},
    {"KH", "Cambodia"},
    {"TD", "Chad"},
    {"LK", "Sri Lanka"},
    {"CD", "DR Congo"},
    {"CG", "Congo Republic"},
    {"CN", "China"},
    {"CL", "Chile"},
    {"KY", "Cayman Islands"},
    {"CC", "Cocos (Keeling) Islands"},
    {"CM", "Cameroon"},
    {"KM", "Comoros"},
    {"CO", "Colombia"},
    {"MP", "Northern Mariana Islands"},
    {"CR", "Costa Rica"},
    {"CF", "Central African Republic"},
    {"CU", "Cuba"},
    {"CV", "Cabo Verde"},
    {"CK", "Cook Islands"},
    {"CY", "Cyprus"},
    {"DK", "Denmark"},
    {"DJ", "Djibouti"},
    {"DM", "Dominica"},
    {"DO", "Dominican Republic"},
    {"EC", "Ecuador"},
    {"EG", "Egypt"},
    {"IE", "Ireland"},
    {"GQ", "Equatorial Guinea"},
    {"EE", "Estonia"},
    {"ER", "Eritrea"},
    {"SV", "El Salvador"},
    {"ET", "Ethiopia"},
    {"CZ", "Czech Republic"},
    {"GF", "French Guiana"},
    {"FI", "Finland"},
    {"FJ", "Fiji"},
    {"FK", "Falkland Islands"},
    {"FM", "Micronesia, Fed. Sts."},
    {"FO", "Faeroe Islands"},
    {"PF", "French Polynesia"},
    {"FR", "France"},
    {"TF", "French Southern Territories"},
    {"GM", "Gambia"},
    {"GA", "Gabon"},
    {"GE", "Georgia"},
    {"GH", "Ghana"},
    {"GI", "Gibraltar"},
    {"GD", "Grenada"},
    {"GG", "Guernsey"},
    {"GL", "Greenland"},
    {"DE", "Germany"},
    {"GP", "Guadeloupe"},
    {"GU", "Guam"},
    {"GR", "Greece"},
    {"GT", "Guatemala"},
    {"GN", "Guinea"},
    {"GY", "Guyana"},
    {"PS", "Palestine"},
    {"HT", "Haiti"},
    {"HK", "Hong Kong"},
    {"HM", "Heard and McDonald Islands"},
    {"HN", "Honduras"},
    {"HR", "Croatia"},
    {"HU", "Hungary"},
    {"IS", "Iceland"},
    {"ID", "Indonesia"},
    {"IM", "Isle of Man"},
    {"IN", "India"},
    {"IO", "British Indian Ocean Territory"},
    {"IR", "Iran"},
    {"IL", "Israel"},
    {"IT", "Italy"},
    {"CI", "Cote d'Ivoire"},
    {"IQ", "Iraq"},
    {"JP", "Japan"},
    {"JE", "Jersey"},
    {"JM", "Jamaica"},
    {"JO", "Jordan"},
    {"KE", "Kenya"},
    {"KG", "Kyrgyz Republic"},
    {"KP", "North Korea"},
    {"KI", "Kiribati"},
    {"KR", "South Korea"},
    {"CX", "Christmas Island"},
    {"KW", "Kuwait"},
    {"KZ", "Kazakhstan"},
    {"LA", "Laos"},
    {"LB", "Lebanon"},
    {"LV", "Latvia"},
    {"LT", "Lithuania"},
    {"LR", "Liberia"},
    {"SK", "Slovakia"},
    {"LS", "Lesotho"},
    {"LU", "Luxembourg"},
    {"LY", "Libya"},
    {"MG", "Madagascar"},
    {"MQ", "Martinique"},
    {"MO", "Macao"},
    {"MD", "Moldova"},
    {"YT", "Mayotte"},
    {"MN", "Mongolia"},
    {"MS", "Montserrat"},
    {"MW", "Malawi"},
    {"ME", "Montenegro"},
    {"MK", "Macedonia"},
    {"ML", "Mali"},
    {"MC", "Monaco"},
    {"MA", "Morocco"},
    {"MU", "Mauritius"},
    {"UM", "Midway Islands/Johnston Atoll/Wake Island"},
    {"MR", "Mauritania"},
    {"MT", "Malta"},
    {"OM", "Oman"},
    {"MV", "Maldives"},
    {"MX", "Mexico"},
    {"MY", "Malaysia"},
    {"MZ", "Mozambique"},
    {"NC", "New Caledonia"},
    {"NU", "Niue"},
    {"NF", "Norfolk Island"},
    {"NE", "Niger"},
    {"VU", "Vanuatu"},
    {"NG", "Nigeria"},
    {"NL", "Netherlands"},
    {"NO", "Norway"},
    {"NP", "Nepal"},
    {"NR", "Nauru"},
    {"SR", "Suriname"},
    {"AN", "Netherlands Antilles"},
    {"NI", "Nicaragua"},
    {"NZ", "New Zealand"},
    {"PY", "Paraguay"},
    {"PN", "Pitcairn"},
    {"PE", "Peru"},
    {"PK", "Pakistan"},
    {"PL", "Poland"},
    {"PA", "Panama"},
    {"PT", "Portugal"},
    {"PG", "Papua New Guinea"},
    {"PW", "Palau"},
    {"GW", "Guinea-Bissau"},
    {"QA", "Qatar"},
    {"RS", "Serbia"},
    {"RE", "Reunion"},
    {"MH", "Marshall Islands"},
    {"RO", "Romania"},
    {"PH", "Philippines"},
    {"PR", "Puerto Rico"},
    {"RU", "Russia"},
    {"RW", "Rwanda"},
    {"SA", "Saudi Arabia"},
    {"PM", "St. Pierre and Miquelon"},
    {"KN", "St. Kitts and Nevis"},
    {"SC", "Seychelles"},
    {"ZA", "South Africa"},
    {"SN", "Senegal"},
    {"SH", "St. Helena"},
    {"SI", "Slovenia"},
    {"SL", "Sierra Leone"},
    {"SG", "Singapore"},
    {"SO", "Somalia"},
    {"ES", "Spain"},
    {"SS", "South Sudan"},
    {"LC", "St. Lucia"},
    {"SD", "Sudan"},
    {"SJ", "Svalbard and Jan Mayen Islands"},
    {"SE", "Sweden"},
    {"GS", "South Georgia and South Sandwich Is."},
    {"SY", "Syria"},
    {"CH", "Switzerland"},
    {"TT", "Trinidad and Tobago"},
    {"TH", "Thailand"},
    {"TJ", "Tajikistan"},
    {"TC", "Turks and Caicos Islands"},
    {"TK", "Tokelau"},
    {"TO", "Tonga"},
    {"TG", "Togo"},
    {"ST", "Sao Tome and Principe"},
    {"TN", "Tunisia"},
    {"TL", "Timor-Leste"},
    {"TR", "Turkey"},
    {"TV", "Tuvalu"},
    {"TW", "Taiwan"},
    {"TM", "Turkmenistan"},
    {"TZ", "Tanzania"},
    {"UG", "Uganda"},
    {"GB", "United Kingdom"},
    {"UA", "Ukraine"},
    {"US", "United States"},
    {"BF", "Burkina Faso"},
    {"UY", "Uruguay"},
    {"UZ", "Uzbekistan"},
    {"VC", "St. Vincent and the Grenadines"},
    {"VE", "Venezuela"},
    {"VG", "British Virgin Islands"},
    {"VN", "Vietnam"},
    {"VI", "United States Virgin Islands"},
    {"NA", "Namibia"},
    {"PS", "Palestine"},
    {"WF", "Wallis and Futuna Islands"},
    {"EH", "Western Sahara"},
    {"WS", "Samoa"},
    {"SZ", "Eswatini"},
    {"YE", "Yemen"},
    {"ZM", "Zambia"},
    {"ZW", "Zimbabwe"}};

const char *lookupCountry(const char *id)
{
    for (auto const &i : countries)
    {
        if (strcmp(id, i.id) == 0)
            return i.name;
    }

    return nullptr;
}
